# Generated by Django 3.2.12 on 2022-04-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='text',
            new_name='content',
        ),
    ]
